version: '3'

networks:
        lan_network:
                driver: bridge
services:
        webappa:pplication:
                hostname: tomcat
                build: .
                ports:
                 - 20200:8080

